#!/bin/bash

function container_ip() {
  container_id=$1
  echo $(docker inspect $container_id | grep IPAddress | cut -d '"' -f 4)
}

function safe_docker_run() {
  container_id=$2
  docker ps | grep $container_id || docker run -d -rm $@
}

function activate_fleet() {
  echo "We need a database"
  safe_docker_run -name rethinkdb -p 8080:8080 crosbymichael/rethinkdb --bind all

  echo "Let's setup configuration storages (only one is needed)"
  safe_docker_run -name etcd -p 4001:4001 coreos/etcd
  safe_docker_run -name mongodb -p 27017:27017 -p 28017:28017 waitingkuo/mongodb

  echo "Then the messenger carrying user orders to Intuition"
  safe_docker_run -name redis dockerfile/redis

  echo "Don't forget the dashboard and its mysql database"
  safe_docker_run -d -name mysql brice/mysql
  safe_docker_run -d -name dashboard -p 3000:3000 \
    -e DB_HOST=$(container_ip "mysql") \
    -e DB_PORT=$(docker port mysql 3306) \
    -e DB_USERNAME=root \
    hivetech/team-dashboard
}

function activate_webservice_intuition() {
  [ -n "$DB_NAME" ] || DB_NAME="portfolios"

  safe_docker_run -name intuition -p 5000:5000
    -e PUSHBULLET_API_KEY=$PUSHBULLET_API_KEY \
    -e QUANDL_API_KEY=$QUANDL_API_KEY \
    -e MAILGUN_API_KEY=$MAILGUN_API_KEY \
    -e TRUEFX_API=$TRUEFX_API \
    -e DB_HOST=$(container_ip "rethinkdb") \
    -e DB_PORT=$(docker port rethinkdb 28015) \
    -e DB_NAME=$DB_NAME \
    -e MSG_HOST=$(container_ip "redis") \
    -e MSG_PORT=$(docker port redis 6379) \
    -e LOG=debug \
    -e LANGUAGE="fr_FR.UTF-8" \
    -e LANG="fr_FR.UTF-8" \
    -e LC_ALL="fr_FR.UTF-8" \
    hivetech/telepathy
}

echo "Intuition Stack setup, powered by docker"
echo "Acticating services"
activate_services_fleet

echo "Acticating Intuition with its RESTFul interface"
activate_webservice_intuition
